export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const BRAND_PRODUCT_REQUEST = "BRAND_PRODUCT_REQUEST";
export const BRAND_PRODUCT_SUCCESS = "BRAND_PRODUCT_SUCCESS";
export const BRAND_PRODUCT_FAIL = "BRAND_PRODUCT_FAIL";

export const ALL_BRANDS_REQUEST = "ALL_BRANDS_REQUEST";
export const ALL_BRANDS_SUCCESS = "ALL_BRANDS_SUCCESS";
export const ALL_BRANDS_FAIL = "ALL_BRANDS_FAIL";



export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST"
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS"
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL"
export const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET"

export const NEW_BRAND_REQUEST = "NEW_BRAND_REQUEST"
export const NEW_BRAND_SUCCESS = "NEW_BRAND_SUCCESS"
export const NEW_BRAND_FAIL = "NEW_BRAND_FAIL"
export const NEW_BRAND_RESET = "NEW_BRAND_RESET"

export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS = "ADMINL_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "AUPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const BRAND_DETAILS_REQUEST = "BRAND_DETAILS_REQUEST";
export const BRAND_DETAILS_SUCCESS = "BRAND_DETAILS_SUCCESS";
export const BRAND_DETAILS_FAIL = "BRAND_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST"
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS"
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL"
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET"

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST"
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS"
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL"


export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST"
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS"
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL"
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET"



export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL"
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET"

export const ADD_SHIPPING_INFO_REQUEST = "ADD_SHIPPING_INFO_REQUEST"
export const ADD_SHIPPING_INFO_SUCCESS = "ADD_SHIPPING_INFO_SUCCESS"
export const ADD_SHIPPING_INFO_FAIL = "ADD_SHIPPING_INFO_FAIL"
export const ADD_SHIPPING_INFO_RESET = "ADD_SHIPPING_INFO_RESET"

export const UPDATE_SHIPPING_INFO_REQUEST = "UPDATE_SHIPPING_INFO_REQUEST"
export const UPDATE_SHIPPING_INFO_SUCCESS = "UPDATE_SHIPPING_INFO_SUCCESS"
export const UPDATE_SHIPPING_INFO_FAIL = "UPDATE_SHIPPING_INFO_FAIL"
export const UPDATE_SHIPPING_INFO_RESET = "UPDATE_SHIPPING_INFO_RESET"

export const GET_SHIPPING_INFO_REQUEST = "GET_SHIPPING_INFO_REQUEST"
export const GET_SHIPPING_INFO_SUCCESS = "GET_SHIPPING_INFO_SUCCESS"
export const GET_SHIPPING_INFO_FAIL = "GET_SHIPPING_INFO_FAIL"
export const GET_SHIPPING_INFO_RESET = "GET_SHIPPING_INFO_RESET"

export const GET_COUPONS_REQUEST = "GET_COUPONS_REQUEST"
export const GET_COUPONS_SUCCESS = "GET_COUPONS_SUCCESS"
export const GET_COUPONS_FAIL = "GET_COUPONS_FAIL"
export const GET_COUPONS_RESET = "GET_COUPONS_RESET"


export const DELETE_SHIPPING_INFO_REQUEST = "DELETE_SHIPPING_INFO_REQUEST"
export const DELETE_SHIPPING_INFO_SUCCESS = "DELETE_SHIPPING_INFO_SUCCESS"
export const DELETE_SHIPPING_INFO_FAIL = "DELETE_SHIPPING_INFO_FAIL"
export const DELETE_SHIPPING_INFO_RESET = "DELETE_SHIPPING_INFO_RESET"

export const GET_DISCOUNT_REQUEST = "GET_DISCOUNT_REQUEST"
export const GET_DISCOUNT_SUCCESS = "GET_DISCOUNT_SUCCESS"
export const GET_DISCOUNT_FAIL = "GET_DISCOUNT_FAIL"
export const GET_DISCOUNT_RESET = "GET_DISCOUNT_RESET"




export const CLEAR_ERRORS = "CLEAR_ERRORS"